name: Delete old workflow runs
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      root_sol:
        description: "Workflow Title"
        required: true
        default: "immortalwrt"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: 删除 immortalwrt
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: 'immortalwrt'         
                  
      - name: 删除自己
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: 'Delete old workflow runs'